version: '3'
services:
    backend:
        image: toxpuro/weatherapp_backend
        ports:
            - 9000:9000
        volumes:
            - ./backend/src:/usr/src/app/src
    frontend:
        image: toxpuro/weatherapp_frontend
        ports:
            - 8000:8000
        volumes:
            - ./frontend/src:/usr/src/app/src
      